import { createContext, useContext, useEffect, useState } from 'react'
import { BrowserRouter, Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import './App.css'

const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:4000/api'
const AuthContext = createContext(null)

async function request(path, options = {}) {
  const response = await fetch(`${API_URL}${path}`, { credentials: 'include', headers: { 'Content-Type': 'application/json', ...options.headers }, ...options })
  const data = response.status === 204 ? null : await response.json()
  if (!response.ok) throw new Error(data?.message || 'Сервер временно недоступен')
  return data
}

function AuthProvider({ children }) {
  const [user, setUser] = useState(null)
  const [loading, setLoading] = useState(true)
  useEffect(() => { request('/auth/me').then((data) => setUser(data.user)).catch(() => {}).finally(() => setLoading(false)) }, [])
  const logout = async () => { await request('/auth/logout', { method: 'POST' }).catch(() => {}); setUser(null) }
  return <AuthContext.Provider value={{ user, setUser, logout, loading }}>{children}</AuthContext.Provider>
}
const useAuth = () => useContext(AuthContext)
const Loader = () => <div className="loader"><span />Загружаем данные...</div>
const ErrorMessage = ({ message }) => message ? <div className="error-message">{message}</div> : null
function ProtectedRoute({ children, admin = false }) { const { user, loading } = useAuth(); if (loading) return <Loader />; if (!user) return <Navigate to="/auth/login" replace />; if (admin && user.role !== 'admin') return <Navigate to="/profile" replace />; return children }

function Layout({ children }) {
  const { user, logout } = useAuth(); const location = useLocation()
  const links = [['/news', 'Новости'], ['/matches', 'Матчи'], ['/teams', 'Команды'], ['/tournaments', 'Турниры']]
  return <><header className="topbar"><Link className="brand" to="/"><span className="brand-mark">FH</span><span>FOOTBALL HUB</span></Link><nav>{links.map(([path, label]) => <Link className={location.pathname === path ? 'active' : ''} key={path} to={path}>{label}</Link>)}</nav><div className="account">{user ? <><Link to="/profile" className="user-chip">{user.name}</Link><button className="button ghost" onClick={logout}>Выйти</button></> : <><Link to="/auth/login">Войти</Link><Link className="button small" to="/auth/register">Регистрация</Link></>}</div></header><main>{children}</main><footer><strong>FOOTBALL HUB</strong><span>Футбол, который всегда рядом</span><span>Лабораторный проект на JavaScript</span></footer></>
}

function MatchCard({ match }) { return <article className="match-card"><div className="match-meta"><span>{match.league}</span><span>{new Date(match.matchDate).toLocaleDateString('ru-RU', { day: '2-digit', month: 'short' })}</span></div><div className="teams"><strong>{match.homeTeam}</strong><span className="versus">{match.status === 'finished' ? `${match.homeScore ?? 0}:${match.awayScore ?? 0}` : 'VS'}</span><strong>{match.awayTeam}</strong></div><small className={`status ${match.status}`}>{match.status === 'finished' ? 'Завершен' : match.status === 'live' ? 'В эфире' : 'Запланирован'}</small></article> }
function Home() { const [matches, setMatches] = useState([]); useEffect(() => { request('/matches').then((data) => setMatches(data.items.slice(0, 3))).catch(() => {}) }, []); return <div className="home"><section className="hero"><div><p className="eyebrow">Сезон 2026 / 27</p><h1>Игра начинается<br /><em>здесь.</em></h1><p className="hero-copy">Новости, расписание и эмоции большого футбола в одном месте.</p><Link className="button" to="/matches">Смотреть матчи <span>→</span></Link></div><div className="hero-ball">⚽</div></section><section className="section"><div className="section-heading"><div><p className="eyebrow">На этой неделе</p><h2>Ближайшие матчи</h2></div><Link to="/matches" className="text-link">Все матчи →</Link></div><div className="match-strip">{matches.map((match) => <MatchCard key={match.id} match={match} />)}</div></section></div> }

function News() {
  const { user } = useAuth(); const [items, setItems] = useState([]); const [search, setSearch] = useState(''); const [category, setCategory] = useState(''); const [sort, setSort] = useState('newest'); const [loading, setLoading] = useState(true); const [error, setError] = useState('')
  const load = () => { setLoading(true); setError(''); request(`/news?search=${encodeURIComponent(search)}&category=${encodeURIComponent(category)}&sort=${sort}`).then((data) => setItems(data.items)).catch((e) => setError(e.message)).finally(() => setLoading(false)) }
  useEffect(() => { load() }, [category, sort])
  const favorite = (id, active) => { if (!user) return; request(`/news/${id}/favorite`, { method: active ? 'DELETE' : 'POST' }).then(() => setItems((current) => current.map((item) => item.id === id ? { ...item, favorite: !active } : item))).catch((e) => setError(e.message)) }
  return <div className="page section"><div className="page-intro"><p className="eyebrow">Лента Football Hub</p><h1>Новости игры</h1><p>Свежие истории, аналитика и события из мира футбола.</p></div><div className="filters"><form onSubmit={(event) => { event.preventDefault(); load() }}><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Поиск по новостям" /><button className="button small">Найти</button></form><select value={category} onChange={(e) => setCategory(e.target.value)}><option value="">Все категории</option><option>Матч дня</option><option>Аналитика</option><option>События</option></select><select value={sort} onChange={(e) => setSort(e.target.value)}><option value="newest">Сначала новые</option><option value="oldest">Сначала старые</option></select></div><ErrorMessage message={error} />{loading ? <Loader /> : <div className="news-grid">{items.map((item) => <article className="news-card" key={item.id}><img src={item.imageUrl} alt="" /><div className="news-card-body"><div className="card-topline"><span>{item.category}</span><button className="heart" onClick={() => favorite(item.id, item.favorite)} aria-label="Добавить в избранное">{item.favorite ? '♥' : '♡'}</button></div><h3>{item.title}</h3><p>{item.excerpt}</p><small>{new Date(item.publishedAt).toLocaleDateString('ru-RU')}</small></div></article>)}</div>}</div>
}

function Matches() { const [items, setItems] = useState([]); const [status, setStatus] = useState(''); useEffect(() => { request(`/matches${status ? `?status=${status}` : ''}`).then((data) => setItems(data.items)) }, [status]); return <div className="page section"><div className="page-intro"><p className="eyebrow">Календарь</p><h1>Матчи</h1><p>Следи за важными играми и результатами команд.</p></div><div className="tabs"><button className={!status ? 'selected' : ''} onClick={() => setStatus('')}>Все</button><button className={status === 'scheduled' ? 'selected' : ''} onClick={() => setStatus('scheduled')}>Предстоящие</button><button className={status === 'finished' ? 'selected' : ''} onClick={() => setStatus('finished')}>Завершенные</button></div><div className="match-list">{items.map((match) => <MatchCard key={match.id} match={match} />)}</div></div> }
function StaticCollection({ title, eyebrow, endpoint, render }) { const [items, setItems] = useState([]); useEffect(() => { request(endpoint).then((data) => setItems(data.items)).catch(() => {}) }, [endpoint]); return <div className="page section"><div className="page-intro"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>Данные загружены с Football Hub API.</p></div><div className="collection-grid">{items.map(render)}</div></div> }
function Teams() { return <StaticCollection title="Команды" eyebrow="Клубы и сборные" endpoint="/teams" render={(team) => <article className="collection-card" key={team.id}><span className="club-badge">{team.shortName}</span><h3>{team.name}</h3><p>{team.city}</p><small>{team.league}</small></article>} /> }
function Tournaments() { return <StaticCollection title="Турниры" eyebrow="Большие соревнования" endpoint="/tournaments" render={(item) => <article className="collection-card" key={item.id}><span className="eyebrow">{item.season}</span><h3>{item.name}</h3><p>{item.description}</p><strong>{item.teams} команд</strong></article>} /> }

function AuthPage({ mode }) { const isRegister = mode === 'register'; const { setUser } = useAuth(); const navigate = useNavigate(); const [form, setForm] = useState({ name: '', email: '', password: '' }); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const submit = async (event) => { event.preventDefault(); setError(''); if (isRegister && form.name.trim().length < 2) return setError('Введите имя минимум из 2 символов'); if (!form.email.includes('@')) return setError('Введите корректный email'); if (form.password.length < 6) return setError('Пароль должен быть не короче 6 символов'); setLoading(true); try { const data = await request(`/auth/${isRegister ? 'register' : 'login'}`, { method: 'POST', body: JSON.stringify(form) }); setUser(data.user); navigate('/profile'); } catch (e) { setError(e.message) } finally { setLoading(false) } }; return <div className="auth-page"><div className="auth-card"><p className="eyebrow">Football Hub</p><h1>{isRegister ? 'Создать аккаунт' : 'С возвращением'}</h1><p>{isRegister ? 'Сохраняй новости и следи за матчами.' : 'Войди, чтобы открыть личную зону.'}</p><form onSubmit={submit}>{isRegister && <input required placeholder="Ваше имя" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} />}<input required type="email" placeholder="Email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} /><input required minLength="6" type="password" placeholder="Пароль" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} /><ErrorMessage message={error} /><button className="button" disabled={loading}>{loading ? 'Проверяем...' : isRegister ? 'Зарегистрироваться' : 'Войти'}</button></form><p className="auth-switch">{isRegister ? 'Уже есть аккаунт?' : 'Еще нет аккаунта?'} <Link to={isRegister ? '/auth/login' : '/auth/register'}>{isRegister ? 'Войти' : 'Регистрация'}</Link></p></div></div> }
function Profile() { const { user } = useAuth(); return <div className="page section profile"><div className="page-intro"><p className="eyebrow">Личная зона</p><h1>Привет, {user.name}</h1><p>Здесь собраны твои настройки и быстрый доступ к сохраненным материалам.</p></div><div className="profile-grid"><div className="profile-card"><span className="avatar">{user.name.slice(0, 1).toUpperCase()}</span><h2>{user.name}</h2><p>{user.email}</p><small>На Football Hub с {new Date(user.createdAt || Date.now()).toLocaleDateString('ru-RU')}</small></div><Link className="profile-action" to="/favorites"><span>♥</span><strong>Мое избранное</strong><small>Сохраненные новости</small></Link>{user.role === 'admin' && <Link className="profile-action" to="/admin"><span>✦</span><strong>Панель администратора</strong><small>Управление контентом</small></Link>}</div></div> }
function Favorites() { const [items, setItems] = useState([]); useEffect(() => { request('/favorites').then((data) => setItems(data.items)).catch(() => {}) }, []); return <div className="page section"><div className="page-intro"><p className="eyebrow">Твоя коллекция</p><h1>Избранное</h1></div><div className="news-grid">{items.map((item) => <article className="news-card compact" key={item.id}><img src={item.imageUrl} alt="" /><div className="news-card-body"><span>{item.category}</span><h3>{item.title}</h3><p>{item.excerpt}</p></div></article>)}</div>{!items.length && <div className="empty">Пока нет сохраненных новостей. Нажми ♡ в ленте.</div>}</div> }
function Admin() { const [form, setForm] = useState({ title: '', excerpt: '', category: 'Матч дня', imageUrl: '' }); const [message, setMessage] = useState(''); const submit = async (event) => { event.preventDefault(); try { await request('/news', { method: 'POST', body: JSON.stringify(form) }); setMessage('Новость опубликована'); setForm({ title: '', excerpt: '', category: 'Матч дня', imageUrl: '' }) } catch (e) { setMessage(e.message) } }; return <div className="page section"><div className="page-intro"><p className="eyebrow">Только для администратора</p><h1>Новая новость</h1></div><form className="admin-form" onSubmit={submit}><input required placeholder="Заголовок" value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} /><textarea required placeholder="Короткое описание" value={form.excerpt} onChange={(e) => setForm({ ...form, excerpt: e.target.value })} /><input required placeholder="URL изображения" value={form.imageUrl} onChange={(e) => setForm({ ...form, imageUrl: e.target.value })} /><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value })}><option>Матч дня</option><option>Аналитика</option><option>События</option></select><button className="button">Опубликовать</button><ErrorMessage message={message} /></form></div> }
function NotFound() { return <div className="not-found"><span>404</span><h1>Страница не найдена</h1><Link className="button" to="/">На главную</Link></div> }
function App() { return <BrowserRouter><AuthProvider><Layout><Routes><Route path="/" element={<Home />} /><Route path="/news" element={<News />} /><Route path="/matches" element={<Matches />} /><Route path="/teams" element={<Teams />} /><Route path="/tournaments" element={<Tournaments />} /><Route path="/auth/login" element={<AuthPage mode="login" />} /><Route path="/auth/register" element={<AuthPage mode="register" />} /><Route path="/profile" element={<ProtectedRoute><Profile /></ProtectedRoute>} /><Route path="/favorites" element={<ProtectedRoute><Favorites /></ProtectedRoute>} /><Route path="/admin" element={<ProtectedRoute admin><Admin /></ProtectedRoute>} /><Route path="*" element={<NotFound />} /></Routes></Layout></AuthProvider></BrowserRouter> }
export default App
